"""
Project Euler Problem 2: Even Fibonacci numbers

Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in this sequence whose values do not exceed four million,
find the sum of the even-valued terms.
"""

def even_fibonacci_sum(limit):
    """
    Calculate the sum of even Fibonacci numbers below the given limit.
    
    Args:
        limit: Maximum value (exclusive)
    
    Returns:
        Sum of even Fibonacci numbers below limit
    """
    total = 0
    a, b = 1, 2  # Start with the first two Fibonacci numbers
    
    while b < limit:
        if b % 2 == 0:
            total += b
        
        # Generate next Fibonacci number
        a, b = b, a + b
    
    return total

def even_fibonacci_sum_optimized(limit):
    """
    Optimized approach using the fact that every third Fibonacci number is even.
    
    The pattern of even Fibonacci numbers: 2, 8, 34, 144, ...
    Each even term F(n) = 4 * F(n-3) + F(n-6)
    """
    if limit <= 2:
        return 0
    
    total = 2  # First even Fibonacci number
    a, b = 2, 8  # First two even Fibonacci numbers
    
    while b < limit:
        total += b
        # Generate next even Fibonacci number
        a, b = b, 4 * b + a
    
    return total

if __name__ == "__main__":
    limit = 4000000
    result = even_fibonacci_sum(limit)
    print(f"Sum of even Fibonacci numbers below {limit}: {result}")
    
    # Verify with optimized approach
    optimized_result = even_fibonacci_sum_optimized(limit)
    print(f"Optimized approach result: {optimized_result}")
    print(f"Results match: {result == optimized_result}")